name: CI/CD - PR to Main

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  test-analyze-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run JUnit Test Suite
        run: ./mvnw test

      - name: Run Checkstyle Static Analysis
        run: ./mvnw checkstyle:check

      - name: Login to GitHub Container Registry
        if: success()
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        if: success()
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:pr-${{ github.event.pull_request.number }}
          docker build -t $IMAGE_NAME -f Dockerfile .

      - name: Push Docker image to Staging
        if: success()
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}:pr-${{ github.event.pull_request.number }}
        run: |
          docker push $IMAGE_NAME
          echo "Docker image pushed: $IMAGE_NAME"